// The cast: ten faculty and thirty students, written out individually so the directory,
// profile pages and member lists read like a real campus rather than a numbered list.
// Every field the schema defines is populated.
//
// `clubs` on a faculty is the slugs they coordinate. `joins` on a student is the clubs
// they belong to as { slug, status }, and `follows` the ones they only subscribe to.
// seedUsers turns both into real ClubMembership / ClubFollow rows.

const FACULTY = [
   {
      email: "priya.nair@college.edu",
      username: "priya.nair",
      name: "Dr. Priya Nair",
      phone: "+91 98450 11204",
      profile: {
         department: "Computer Science & Engineering",
         designation: "Associate Professor",
         officeLocation: "CSE Block, Room 214",
         bio: "Works on applied machine learning for low-resource languages, with a side interest in making research actually reproducible. Runs the AI Collective's reading group and has been dragging undergrads to conferences since 2016. Office hours Tuesday and Thursday afternoons — walk in, no appointment needed.",
         linkedinUrl: "https://linkedin.com/in/priya-nair-ml",
         portfolioUrl: "https://priyanair.research.college.edu",
         expertise: ["Machine Learning", "NLP", "Research Methods", "Python"],
      },
      clubs: ["ai-club", "quantum-computing"],
      lastLoginDaysAgo: 0.2,
   },
   {
      email: "rahul.deshpande@college.edu",
      username: "rahul.deshpande",
      name: "Prof. Rahul Deshpande",
      phone: "+91 98450 33871",
      profile: {
         department: "Computer Science & Engineering",
         designation: "Assistant Professor",
         officeLocation: "CSE Block, Room 108",
         bio: "Teaches algorithms and coaches the ICPC teams. Believes most people quit competitive programming about two weeks before it starts making sense, so the club's training ladder is built specifically to get you past that point.",
         linkedinUrl: "https://linkedin.com/in/rahul-deshpande-algo",
         portfolioUrl: "https://codeforces.com/profile/rdeshpande",
         expertise: ["Algorithms", "Data Structures", "Competitive Programming", "C++"],
      },
      clubs: ["codeforces-nitk"],
      lastLoginDaysAgo: 1.1,
   },
   {
      email: "meera.krishnan@college.edu",
      username: "meera.krishnan",
      name: "Dr. Meera Krishnan",
      phone: "+91 98450 47720",
      profile: {
         department: "Information Technology",
         designation: "Professor & Head of Department",
         officeLocation: "IT Block, Room 301",
         bio: "Distributed systems by training, web platforms by necessity. Pushed for the campus to run its own services instead of buying them, which is how the WebDev Society ended up maintaining half the department's internal tools.",
         linkedinUrl: "https://linkedin.com/in/meera-krishnan-it",
         portfolioUrl: "https://meerakrishnan.dev",
         expertise: ["Distributed Systems", "Web Architecture", "Databases", "Mentoring"],
      },
      clubs: ["webdev-society"],
      lastLoginDaysAgo: 0.6,
   },
   {
      email: "arun.venkatesh@college.edu",
      username: "arun.venkatesh",
      name: "Dr. Arun Venkatesh",
      phone: "+91 98450 62319",
      profile: {
         department: "Management Studies",
         designation: "Professor",
         officeLocation: "MS Block, Room 12",
         bio: "Spent eleven years in industry before teaching, including two failed startups he will happily tell you about in detail. Mentors E-Cell teams through the pitch cycle and keeps the alumni investor network warm.",
         linkedinUrl: "https://linkedin.com/in/arun-venkatesh-ecell",
         portfolioUrl: "https://arunventures.substack.com",
         expertise: ["Entrepreneurship", "Product Strategy", "Fundraising", "Go-to-Market"],
      },
      clubs: ["e-cell"],
      lastLoginDaysAgo: 2.4,
   },
   {
      email: "sanjay.rao@college.edu",
      username: "sanjay.rao",
      name: "Dr. Sanjay Rao",
      phone: "+91 98450 70045",
      profile: {
         department: "Mechanical Engineering",
         designation: "Associate Professor",
         officeLocation: "Workshop Annexe, Room 4",
         bio: "Control systems and mechatronics. Runs the robotics lab on the principle that a bot you have not crashed is a bot you have not tested. Holds the keys to the fabrication shop, which makes him extremely popular around competition season.",
         linkedinUrl: "https://linkedin.com/in/sanjay-rao-robotics",
         portfolioUrl: "https://roboticslab.college.edu/people/sanjay",
         expertise: ["Control Systems", "Mechatronics", "ROS", "Embedded C"],
      },
      clubs: ["robotics-club"],
      lastLoginDaysAgo: 0.9,
   },
   {
      email: "kavya.menon@college.edu",
      username: "kavya.menon",
      name: "Prof. Kavya Menon",
      phone: "+91 98450 85562",
      profile: {
         department: "Design",
         designation: "Assistant Professor",
         officeLocation: "Design Studio, Mezzanine",
         bio: "Interaction design and visual systems. Came from a decade in product studios and still takes freelance work so the critiques stay honest. Every poster you have seen on campus this year went through her review.",
         linkedinUrl: "https://linkedin.com/in/kavya-menon-design",
         portfolioUrl: "https://kavyamenon.design",
         expertise: ["Interaction Design", "Design Systems", "Typography", "Figma"],
      },
      clubs: ["design-studio"],
      lastLoginDaysAgo: 0.4,
   },
   {
      email: "ananth.subramanian@college.edu",
      username: "ananth.subramanian",
      name: "Dr. Ananth Subramanian",
      phone: "+91 98450 90183",
      profile: {
         department: "Humanities & Social Sciences",
         designation: "Professor",
         officeLocation: "HSS Block, Room 9",
         bio: "Comparative literature, with a stubborn attachment to the short story. Has edited the campus magazine through fourteen issues and insists the submission deadline is real, which it is.",
         linkedinUrl: "https://linkedin.com/in/ananth-subramanian",
         portfolioUrl: "https://spinaker.college.edu/editors",
         expertise: ["Comparative Literature", "Creative Writing", "Editing", "Debate"],
      },
      clubs: ["literary-society"],
      lastLoginDaysAgo: 3.2,
   },
   {
      email: "farah.qureshi@college.edu",
      username: "farah.qureshi",
      name: "Prof. Farah Qureshi",
      phone: "+91 98450 26640",
      profile: {
         department: "Humanities & Social Sciences",
         designation: "Assistant Professor",
         officeLocation: "Music Room, Cultural Centre",
         bio: "Trained in Hindustani classical, teaches music theory, and is entirely relaxed about the fact that most of the club would rather play metal. Runs the Friday jam and keeps the instrument inventory.",
         linkedinUrl: "https://linkedin.com/in/farah-qureshi-music",
         portfolioUrl: "https://soundcloud.com/farahqureshi",
         expertise: ["Music Theory", "Hindustani Classical", "Ensemble Direction", "Audio Production"],
      },
      clubs: ["music-club", "film-makers"],
      lastLoginDaysAgo: 1.7,
   },
   {
      email: "vikram.joshi@college.edu",
      username: "vikram.joshi",
      name: "Dr. Vikram Joshi",
      phone: "+91 98450 55917",
      profile: {
         department: "Electronics & Communication",
         designation: "Associate Professor",
         officeLocation: "ECE Block, Room 118",
         bio: "Signal processing and optics, which is a longer way of saying he is the reason the photography club owns a decent set of lenses. Takes the wildlife photowalks himself whenever the timing works out.",
         linkedinUrl: "https://linkedin.com/in/vikram-joshi-ece",
         portfolioUrl: "https://vikramjoshi.photo",
         expertise: ["Signal Processing", "Optics", "Photography", "MATLAB"],
      },
      clubs: ["photography-club"],
      lastLoginDaysAgo: 5.5,
   },
   {
      email: "deepak.shetty@college.edu",
      username: "deepak.shetty",
      name: "Prof. Deepak Shetty",
      phone: "+91 98450 38874",
      profile: {
         department: "Physical Education",
         designation: "Director of Sports",
         officeLocation: "Sports Complex, Admin Wing",
         bio: "Runs the inter-college calendar, the grounds booking, and the annual argument about who gets the main field on a Saturday. Played state-level cricket, coaches the football side, and books the physio.",
         linkedinUrl: "https://linkedin.com/in/deepak-shetty-sports",
         portfolioUrl: "https://sports.college.edu/staff",
         expertise: ["Sports Administration", "Cricket", "Football", "Athlete Wellbeing"],
      },
      clubs: ["sports-council"],
      lastLoginDaysAgo: 0.8,
   },
];

// Thirty students. Departments, years and interests are spread so the directory filters,
// the profile pages and the club rosters all have something real to show.
const STUDENTS = [
   {
      email: "aarav.sharma@college.edu", username: "aaravsharma", name: "Aarav Sharma",
      phone: "+91 99012 40118",
      profile: {
         department: "Computer Science & Engineering", year: "3",
         bio: "Third-year CSE, mostly interested in what happens after the model trains — serving, latency, the boring parts nobody demos. Spent last summer interning on a recommendations team and came back with strong opinions about feature stores.",
         linkedinUrl: "https://linkedin.com/in/aarav-sharma-cse",
         githubUrl: "https://github.com/aaravsharma",
         portfolioUrl: "https://aarav.dev",
         tags: ["ML Engineering", "Backend", "Open Source"],
      },
      skills: [
         { name: "Python", level: 88, category: "Languages" },
         { name: "PyTorch", level: 74, category: "ML" },
         { name: "Docker", level: 61, category: "Infrastructure" },
         { name: "PostgreSQL", level: 55, category: "Databases" },
      ],
      interests: ["Machine Learning", "Systems", "Chess"],
      joins: [{ slug: "ai-club", status: "approved" }, { slug: "webdev-society", status: "approved" }],
      follows: ["codeforces-nitk", "e-cell"],
      lastLoginDaysAgo: 0.1,
   },
   {
      email: "diya.patel@college.edu", username: "diyapatel", name: "Diya Patel",
      phone: "+91 99012 55273",
      profile: {
         department: "Design", year: "2",
         bio: "Second-year design student. Started out doing event posters for free and now runs the studio's brand review. Currently obsessed with variable fonts and with getting people to stop centring body text.",
         linkedinUrl: "https://linkedin.com/in/diya-patel-design",
         githubUrl: "https://github.com/diyapatel",
         portfolioUrl: "https://diyapatel.design",
         tags: ["Visual Design", "Branding", "Motion"],
      },
      skills: [
         { name: "Figma", level: 92, category: "Design" },
         { name: "After Effects", level: 70, category: "Motion" },
         { name: "Illustrator", level: 81, category: "Design" },
         { name: "HTML/CSS", level: 58, category: "Web" },
      ],
      interests: ["Typography", "Illustration", "Film"],
      joins: [{ slug: "design-studio", status: "approved" }, { slug: "film-makers", status: "approved" }],
      follows: ["photography-club"],
      lastLoginDaysAgo: 0.3,
   },
   {
      email: "vivaan.reddy@college.edu", username: "vivaanreddy", name: "Vivaan Reddy",
      phone: "+91 99012 61904",
      profile: {
         department: "Computer Science & Engineering", year: "4",
         bio: "Final year. Two-time ICPC regionalist, currently more interested in compilers than in contests. Writes up editorials for the club's practice rounds because explaining a solution is the only way to be sure you understood it.",
         linkedinUrl: "https://linkedin.com/in/vivaan-reddy",
         githubUrl: "https://github.com/vivaanreddy",
         portfolioUrl: "https://vivaan.codes",
         tags: ["Competitive Programming", "Compilers", "C++"],
      },
      skills: [
         { name: "C++", level: 95, category: "Languages" },
         { name: "Algorithms", level: 90, category: "CS Core" },
         { name: "Rust", level: 48, category: "Languages" },
         { name: "LaTeX", level: 66, category: "Tools" },
      ],
      interests: ["Algorithms", "Programming Languages", "Cycling"],
      joins: [{ slug: "codeforces-nitk", status: "approved" }, { slug: "ai-club", status: "approved" }, { slug: "quantum-computing", status: "approved" }],
      follows: [],
      lastLoginDaysAgo: 0.5,
   },
   {
      email: "ananya.iyer@college.edu", username: "ananyaiyer", name: "Ananya Iyer",
      phone: "+91 99012 73340",
      profile: {
         department: "Information Technology", year: "3",
         bio: "Builds web things. Maintains the department's internal attendance tool, which taught her more about migrations and angry users than any course has. Runs the society's Wednesday pairing sessions.",
         linkedinUrl: "https://linkedin.com/in/ananya-iyer-it",
         githubUrl: "https://github.com/ananyaiyer",
         portfolioUrl: "https://ananyaiyer.dev",
         tags: ["Full Stack", "React", "Developer Experience"],
      },
      skills: [
         { name: "React", level: 87, category: "Web" },
         { name: "Node.js", level: 79, category: "Web" },
         { name: "TypeScript", level: 82, category: "Languages" },
         { name: "MongoDB", level: 64, category: "Databases" },
      ],
      interests: ["Web Development", "Teaching", "Board Games"],
      joins: [{ slug: "webdev-society", status: "approved" }, { slug: "design-studio", status: "approved" }],
      follows: ["ai-club"],
      lastLoginDaysAgo: 0.2,
   },
   {
      email: "aditya.nair@college.edu", username: "adityanair", name: "Aditya Nair",
      phone: "+91 99012 88461",
      profile: {
         department: "Mechanical Engineering", year: "4",
         bio: "Robotics, specifically legged locomotion. Has spent two years and an unreasonable amount of the lab budget on a quadruped that now walks about four metres before falling over. Progress is progress.",
         linkedinUrl: "https://linkedin.com/in/aditya-nair-robotics",
         githubUrl: "https://github.com/adityanair",
         portfolioUrl: "https://adityanair.engineering",
         tags: ["Robotics", "Control Systems", "CAD"],
      },
      skills: [
         { name: "ROS", level: 84, category: "Robotics" },
         { name: "SolidWorks", level: 77, category: "CAD" },
         { name: "Embedded C", level: 72, category: "Languages" },
         { name: "Python", level: 68, category: "Languages" },
      ],
      interests: ["Robotics", "Manufacturing", "Trekking"],
      joins: [{ slug: "robotics-club", status: "approved" }],
      follows: ["ai-club", "sports-council"],
      lastLoginDaysAgo: 1.4,
   },
   {
      email: "ishita.rao@college.edu", username: "ishitarao", name: "Ishita Rao",
      phone: "+91 99012 94012",
      profile: {
         department: "Management Studies", year: "postgrad",
         bio: "MBA candidate, previously two years at a logistics startup where she watched a good product lose to a worse one with better distribution. Now runs E-Cell's mentor matching and is blunt in pitch reviews.",
         linkedinUrl: "https://linkedin.com/in/ishita-rao-mba",
         githubUrl: "https://github.com/ishitarao",
         portfolioUrl: "https://ishitarao.notion.site",
         tags: ["Product", "Go-to-Market", "Operations"],
      },
      skills: [
         { name: "Market Research", level: 86, category: "Business" },
         { name: "Financial Modelling", level: 74, category: "Business" },
         { name: "SQL", level: 63, category: "Data" },
         { name: "Pitch Coaching", level: 80, category: "Business" },
      ],
      interests: ["Startups", "Economics", "Long-form Journalism"],
      joins: [{ slug: "e-cell", status: "approved" }, { slug: "literary-society", status: "approved" }],
      follows: ["design-studio"],
      lastLoginDaysAgo: 0.7,
   },
   {
      email: "arjun.menon@college.edu", username: "arjunmenon", name: "Arjun Menon",
      phone: "+91 99013 10556",
      profile: {
         department: "Electronics & Communication", year: "2",
         bio: "Second year, into embedded audio. Built a guitar pedal from scratch last term, which mostly works. Plays bass for one of the club bands and handles the mixing desk at open mics.",
         linkedinUrl: "https://linkedin.com/in/arjun-menon-ece",
         githubUrl: "https://github.com/arjunmenon",
         portfolioUrl: "https://arjunmenon.audio",
         tags: ["Embedded", "Audio DSP", "Music"],
      },
      skills: [
         { name: "Embedded C", level: 69, category: "Languages" },
         { name: "PCB Design", level: 58, category: "Hardware" },
         { name: "Ableton Live", level: 75, category: "Audio" },
         { name: "MATLAB", level: 52, category: "Tools" },
      ],
      interests: ["Music Production", "Electronics", "Vinyl"],
      joins: [{ slug: "music-club", status: "approved" }, { slug: "robotics-club", status: "pending" }],
      follows: ["film-makers"],
      lastLoginDaysAgo: 2.1,
   },
   {
      email: "saanvi.gupta@college.edu", username: "saanvigupta", name: "Saanvi Gupta",
      phone: "+91 99013 22890",
      profile: {
         department: "Computer Science & Engineering", year: "1",
         bio: "First year, still working out what she likes. So far: anything with a visible output. Joined three clubs in the first month and has been to every single session, which is more than most.",
         linkedinUrl: "https://linkedin.com/in/saanvi-gupta",
         githubUrl: "https://github.com/saanvigupta",
         portfolioUrl: "https://saanvi.pages.dev",
         tags: ["Beginner", "Frontend", "Curious"],
      },
      skills: [
         { name: "Python", level: 42, category: "Languages" },
         { name: "HTML/CSS", level: 55, category: "Web" },
         { name: "Git", level: 38, category: "Tools" },
      ],
      interests: ["Web Development", "Photography", "Anime"],
      joins: [{ slug: "webdev-society", status: "approved" }, { slug: "photography-club", status: "pending" }],
      follows: ["ai-club", "design-studio", "music-club"],
      lastLoginDaysAgo: 0.05,
   },
   {
      email: "reyansh.kumar@college.edu", username: "reyanshkumar", name: "Reyansh Kumar",
      phone: "+91 99013 33127",
      profile: {
         department: "Computer Science & Engineering", year: "3",
         bio: "Security-minded. Runs the informal CTF group that meets whenever a good competition is on, which is roughly every other weekend. Found two real bugs in the campus portal and reported both properly.",
         linkedinUrl: "https://linkedin.com/in/reyansh-kumar-sec",
         githubUrl: "https://github.com/reyanshkumar",
         portfolioUrl: "https://reyansh.sh",
         tags: ["Security", "CTF", "Linux"],
      },
      skills: [
         { name: "Linux", level: 85, category: "Systems" },
         { name: "Python", level: 79, category: "Languages" },
         { name: "Burp Suite", level: 66, category: "Security" },
         { name: "Networking", level: 71, category: "Systems" },
      ],
      interests: ["Security", "Systems", "Puzzles"],
      joins: [{ slug: "codeforces-nitk", status: "approved" }, { slug: "webdev-society", status: "approved" }],
      follows: ["quantum-computing"],
      lastLoginDaysAgo: 1.9,
   },
   {
      email: "myra.joshi@college.edu", username: "myrajoshi", name: "Myra Joshi",
      phone: "+91 99013 44778",
      profile: {
         department: "Humanities & Social Sciences", year: "2",
         bio: "Writes short fiction, edits the magazine's prose section, and will argue about the Oxford comma at length. Won the inter-college slam last year with a piece she wrote on the bus there.",
         linkedinUrl: "https://linkedin.com/in/myra-joshi-writes",
         githubUrl: "https://github.com/myrajoshi",
         portfolioUrl: "https://myrajoshi.substack.com",
         tags: ["Fiction", "Editing", "Poetry"],
      },
      skills: [
         { name: "Creative Writing", level: 89, category: "Writing" },
         { name: "Copy Editing", level: 82, category: "Writing" },
         { name: "Public Speaking", level: 76, category: "Communication" },
      ],
      interests: ["Literature", "Theatre", "Journalism"],
      joins: [{ slug: "literary-society", status: "approved" }, { slug: "film-makers", status: "approved" }],
      follows: ["music-club"],
      lastLoginDaysAgo: 3.3,
   },
];

STUDENTS.push(
   {
      email: "kabir.singh@college.edu", username: "kabirsingh", name: "Kabir Singh",
      phone: "+91 99013 51203",
      profile: {
         department: "Civil Engineering", year: "4",
         bio: "Civil final year, captains the football side. Handles fixture scheduling for the council, which is a thankless job involving four grounds, nine teams and the monsoon.",
         linkedinUrl: "https://linkedin.com/in/kabir-singh-civil",
         githubUrl: "https://github.com/kabirsingh",
         portfolioUrl: "https://kabirsingh.me",
         tags: ["Sports", "Structures", "Logistics"],
      },
      skills: [
         { name: "AutoCAD", level: 78, category: "CAD" },
         { name: "Project Planning", level: 71, category: "Management" },
         { name: "Football Coaching", level: 84, category: "Sports" },
      ],
      interests: ["Football", "Infrastructure", "Fitness"],
      joins: [{ slug: "sports-council", status: "approved" }],
      follows: ["photography-club"],
      lastLoginDaysAgo: 1.2,
   },
   {
      email: "aadhya.pillai@college.edu", username: "aadhyapillai", name: "Aadhya Pillai",
      phone: "+91 99013 66495",
      profile: {
         department: "Electrical & Electronics", year: "3",
         bio: "Power systems by day, astrophotography by night. Owns the club's only star tracker and lends it out on the condition that you write up what you shot.",
         linkedinUrl: "https://linkedin.com/in/aadhya-pillai",
         githubUrl: "https://github.com/aadhyapillai",
         portfolioUrl: "https://aadhya.photo",
         tags: ["Astrophotography", "Power Systems", "Long Exposure"],
      },
      skills: [
         { name: "Lightroom", level: 83, category: "Photography" },
         { name: "PSpice", level: 64, category: "Simulation" },
         { name: "Python", level: 59, category: "Languages" },
      ],
      interests: ["Astronomy", "Photography", "Hiking"],
      joins: [{ slug: "photography-club", status: "approved" }],
      follows: ["quantum-computing", "ai-club"],
      lastLoginDaysAgo: 4.1,
   },
   {
      email: "krishna.verma@college.edu", username: "krishnaverma", name: "Krishna Verma",
      phone: "+91 99013 77841",
      profile: {
         department: "Computer Science & Engineering", year: "postgrad",
         bio: "MTech, thesis on error mitigation for near-term quantum devices. Started the reading group because there was nobody on campus to talk to about it; there are now eleven of them.",
         linkedinUrl: "https://linkedin.com/in/krishna-verma-quantum",
         githubUrl: "https://github.com/krishnaverma",
         portfolioUrl: "https://krishnaverma.quantum.blog",
         tags: ["Quantum Computing", "Research", "Qiskit"],
      },
      skills: [
         { name: "Qiskit", level: 81, category: "Quantum" },
         { name: "Linear Algebra", level: 88, category: "Maths" },
         { name: "Python", level: 84, category: "Languages" },
         { name: "LaTeX", level: 79, category: "Tools" },
      ],
      interests: ["Quantum Information", "Mathematics", "Cooking"],
      joins: [{ slug: "quantum-computing", status: "approved" }, { slug: "ai-club", status: "approved" }],
      follows: ["codeforces-nitk"],
      lastLoginDaysAgo: 0.9,
   },
   {
      email: "anika.desai@college.edu", username: "anikadesai", name: "Anika Desai",
      phone: "+91 99013 82360",
      profile: {
         department: "Design", year: "4",
         bio: "Final-year design, focused on service design and research. Ran the accessibility audit of the campus app and produced a report nobody could ignore, which is the point.",
         linkedinUrl: "https://linkedin.com/in/anika-desai-ux",
         githubUrl: "https://github.com/anikadesai",
         portfolioUrl: "https://anikadesai.studio",
         tags: ["UX Research", "Accessibility", "Service Design"],
      },
      skills: [
         { name: "User Research", level: 90, category: "Design" },
         { name: "Figma", level: 85, category: "Design" },
         { name: "Accessibility", level: 80, category: "Design" },
         { name: "Prototyping", level: 77, category: "Design" },
      ],
      interests: ["Accessibility", "Ceramics", "Podcasts"],
      joins: [{ slug: "design-studio", status: "approved" }, { slug: "e-cell", status: "approved" }],
      follows: ["literary-society"],
      lastLoginDaysAgo: 0.6,
   },
   {
      email: "rohan.bhat@college.edu", username: "rohanbhat", name: "Rohan Bhat",
      phone: "+91 99013 90714",
      profile: {
         department: "Metallurgical Engineering", year: "2",
         bio: "Second year metallurgy, which he insists is more interesting than it sounds. Does the drone airframes for the robotics team because he is the only one who understands why the last one snapped.",
         linkedinUrl: "https://linkedin.com/in/rohan-bhat-mme",
         githubUrl: "https://github.com/rohanbhat",
         portfolioUrl: "https://rohanbhat.tech",
         tags: ["Materials", "Drones", "Fabrication"],
      },
      skills: [
         { name: "Fusion 360", level: 70, category: "CAD" },
         { name: "Materials Testing", level: 66, category: "Engineering" },
         { name: "3D Printing", level: 74, category: "Fabrication" },
      ],
      interests: ["Drones", "Materials Science", "Cricket"],
      joins: [{ slug: "robotics-club", status: "approved" }, { slug: "sports-council", status: "approved" }],
      follows: [],
      lastLoginDaysAgo: 2.8,
   },
   {
      email: "navya.shetty@college.edu", username: "navyashetty", name: "Navya Shetty",
      phone: "+91 99014 01925",
      profile: {
         department: "Information Technology", year: "2",
         bio: "Does the club's video work — shoots, edits, and has strong feelings about b-roll. Cut the recruitment film that doubled sign-ups last semester.",
         linkedinUrl: "https://linkedin.com/in/navya-shetty-film",
         githubUrl: "https://github.com/navyashetty",
         portfolioUrl: "https://vimeo.com/navyashetty",
         tags: ["Editing", "Cinematography", "Colour"],
      },
      skills: [
         { name: "DaVinci Resolve", level: 86, category: "Video" },
         { name: "Premiere Pro", level: 78, category: "Video" },
         { name: "Cinematography", level: 72, category: "Video" },
         { name: "JavaScript", level: 49, category: "Languages" },
      ],
      interests: ["Film", "Colour Grading", "Travel"],
      joins: [{ slug: "film-makers", status: "approved" }, { slug: "photography-club", status: "approved" }],
      follows: ["design-studio", "music-club"],
      lastLoginDaysAgo: 1.5,
   },
   {
      email: "dhruv.agarwal@college.edu", username: "dhruvagarwal", name: "Dhruv Agarwal",
      phone: "+91 99014 13488",
      profile: {
         department: "Management Studies", year: "1",
         bio: "First-year management, already running a small reselling operation out of his hostel room. E-Cell's youngest member and the one most likely to ask what your margins are.",
         linkedinUrl: "https://linkedin.com/in/dhruv-agarwal-biz",
         githubUrl: "https://github.com/dhruvagarwal",
         portfolioUrl: "https://dhruvagarwal.co",
         tags: ["Sales", "Growth", "Bootstrapping"],
      },
      skills: [
         { name: "Sales", level: 68, category: "Business" },
         { name: "Excel", level: 72, category: "Tools" },
         { name: "Copywriting", level: 61, category: "Marketing" },
      ],
      interests: ["Startups", "Marketing", "Basketball"],
      joins: [{ slug: "e-cell", status: "approved" }],
      follows: ["webdev-society", "sports-council"],
      lastLoginDaysAgo: 0.4,
   },
   {
      email: "kiara.fernandes@college.edu", username: "kiarafernandes", name: "Kiara Fernandes",
      phone: "+91 99014 26031",
      profile: {
         department: "Humanities & Social Sciences", year: "3",
         bio: "Sings lead for two of the campus bands, which is two more than she planned. Also organises the Friday jam and keeps the sign-up sheet honest.",
         linkedinUrl: "https://linkedin.com/in/kiara-fernandes",
         githubUrl: "https://github.com/kiarafernandes",
         portfolioUrl: "https://soundcloud.com/kiarafernandes",
         tags: ["Vocals", "Songwriting", "Live Sound"],
      },
      skills: [
         { name: "Vocals", level: 91, category: "Music" },
         { name: "Songwriting", level: 74, category: "Music" },
         { name: "Guitar", level: 63, category: "Music" },
      ],
      interests: ["Music", "Theatre", "Poetry"],
      joins: [{ slug: "music-club", status: "approved" }, { slug: "literary-society", status: "approved" }],
      follows: ["film-makers"],
      lastLoginDaysAgo: 0.8,
   },
   {
      email: "ayaan.khan@college.edu", username: "ayaankhan", name: "Ayaan Khan",
      phone: "+91 99014 37652",
      profile: {
         department: "Chemical Engineering", year: "3",
         bio: "Chemical engineering, distance runner, and the person who actually shows up at 6am for training. Manages the council's fitness programme and the injury log.",
         linkedinUrl: "https://linkedin.com/in/ayaan-khan-che",
         githubUrl: "https://github.com/ayaankhan",
         portfolioUrl: "https://ayaankhan.run",
         tags: ["Athletics", "Process Engineering", "Endurance"],
      },
      skills: [
         { name: "Aspen Plus", level: 62, category: "Simulation" },
         { name: "Data Analysis", level: 58, category: "Data" },
         { name: "Athletics Coaching", level: 79, category: "Sports" },
      ],
      interests: ["Running", "Nutrition", "Chemistry"],
      joins: [{ slug: "sports-council", status: "approved" }],
      follows: ["ai-club"],
      lastLoginDaysAgo: 6.2,
   },
   {
      email: "tara.mishra@college.edu", username: "taramishra", name: "Tara Mishra",
      phone: "+91 99014 48119",
      profile: {
         department: "Computer Science & Engineering", year: "2",
         bio: "Into data visualisation and the specific pleasure of a chart that explains itself. Built the dashboard the sports council uses for tournament standings.",
         linkedinUrl: "https://linkedin.com/in/tara-mishra-data",
         githubUrl: "https://github.com/taramishra",
         portfolioUrl: "https://taramishra.observablehq.cloud",
         tags: ["Data Viz", "D3", "Analytics"],
      },
      skills: [
         { name: "D3.js", level: 76, category: "Web" },
         { name: "Python", level: 71, category: "Languages" },
         { name: "Pandas", level: 69, category: "Data" },
         { name: "SQL", level: 65, category: "Data" },
      ],
      interests: ["Data Visualisation", "Statistics", "Design"],
      joins: [{ slug: "ai-club", status: "approved" }, { slug: "design-studio", status: "approved" }],
      follows: ["webdev-society"],
      lastLoginDaysAgo: 0.25,
   },
);

STUDENTS.push(
   {
      email: "vihaan.chauhan@college.edu", username: "vihaanchauhan", name: "Vihaan Chauhan",
      phone: "+91 99014 59274",
      profile: {
         department: "Computer Science & Engineering", year: "4",
         bio: "Interned at two infra teams and came back convinced that most outages are configuration, not code. Keeps the society's deployment pipeline running and writes the postmortems.",
         linkedinUrl: "https://linkedin.com/in/vihaan-chauhan-infra",
         githubUrl: "https://github.com/vihaanchauhan",
         portfolioUrl: "https://vihaan.systems",
         tags: ["DevOps", "Kubernetes", "Reliability"],
      },
      skills: [
         { name: "Kubernetes", level: 80, category: "Infrastructure" },
         { name: "Terraform", level: 73, category: "Infrastructure" },
         { name: "Go", level: 67, category: "Languages" },
         { name: "Linux", level: 82, category: "Systems" },
      ],
      interests: ["Infrastructure", "Observability", "Coffee"],
      joins: [{ slug: "webdev-society", status: "approved" }, { slug: "codeforces-nitk", status: "approved" }],
      follows: ["e-cell"],
      lastLoginDaysAgo: 1.05,
   },
   {
      email: "riya.das@college.edu", username: "riyadas", name: "Riya Das",
      phone: "+91 99014 60830",
      profile: {
         department: "Electronics & Communication", year: "1",
         bio: "First year, joined the robotics club in week two and has not missed a build night since. Currently learning to solder without setting off the alarm.",
         linkedinUrl: "https://linkedin.com/in/riya-das-ece",
         githubUrl: "https://github.com/riyadas",
         portfolioUrl: "https://riyadas.dev",
         tags: ["Beginner", "Electronics", "Hardware"],
      },
      skills: [
         { name: "Arduino", level: 45, category: "Hardware" },
         { name: "C", level: 40, category: "Languages" },
         { name: "Soldering", level: 33, category: "Fabrication" },
      ],
      interests: ["Robotics", "Electronics", "Sketching"],
      joins: [{ slug: "robotics-club", status: "approved" }],
      follows: ["ai-club", "photography-club"],
      lastLoginDaysAgo: 0.15,
   },
   {
      email: "shaurya.kulkarni@college.edu", username: "shauryakulkarni", name: "Shaurya Kulkarni",
      phone: "+91 99014 71962",
      profile: {
         department: "Information Technology", year: "3",
         bio: "Writes the club's practice problems and marks them by hand because the judge keeps timing out. Fastest editorial turnaround on the team.",
         linkedinUrl: "https://linkedin.com/in/shaurya-kulkarni",
         githubUrl: "https://github.com/shauryakulkarni",
         portfolioUrl: "https://shaurya.codes",
         tags: ["Competitive Programming", "Problem Setting", "Java"],
      },
      skills: [
         { name: "Java", level: 81, category: "Languages" },
         { name: "Algorithms", level: 83, category: "CS Core" },
         { name: "C++", level: 76, category: "Languages" },
      ],
      interests: ["Algorithms", "Teaching", "Badminton"],
      joins: [{ slug: "codeforces-nitk", status: "approved" }, { slug: "sports-council", status: "approved" }],
      follows: [],
      lastLoginDaysAgo: 2.6,
   },
   {
      email: "meera.banerjee@college.edu", username: "meerabanerjee", name: "Meera Banerjee",
      phone: "+91 99014 83407",
      profile: {
         department: "Design", year: "3",
         bio: "Illustration and print. Does the magazine's covers and has a risograph in the studio that she guards carefully. Teaches the zine-making workshop every term.",
         linkedinUrl: "https://linkedin.com/in/meera-banerjee-art",
         githubUrl: "https://github.com/meerabanerjee",
         portfolioUrl: "https://meerabanerjee.ink",
         tags: ["Illustration", "Print", "Zines"],
      },
      skills: [
         { name: "Procreate", level: 88, category: "Illustration" },
         { name: "Risograph", level: 70, category: "Print" },
         { name: "InDesign", level: 74, category: "Design" },
      ],
      interests: ["Illustration", "Printmaking", "Comics"],
      joins: [{ slug: "design-studio", status: "approved" }, { slug: "literary-society", status: "approved" }],
      follows: ["film-makers"],
      lastLoginDaysAgo: 1.8,
   },
   {
      email: "nikhil.pillai@college.edu", username: "nikhilpillai", name: "Nikhil Pillai",
      phone: "+91 99014 94518",
      profile: {
         department: "Mechanical Engineering", year: "postgrad",
         bio: "MTech in thermal systems. Came back to the robotics lab after a year in industry and now mentors the first-years through their first build, which he says is the best part of the week.",
         linkedinUrl: "https://linkedin.com/in/nikhil-pillai-me",
         githubUrl: "https://github.com/nikhilpillai",
         portfolioUrl: "https://nikhilpillai.engineer",
         tags: ["Thermal Systems", "Mentoring", "Simulation"],
      },
      skills: [
         { name: "ANSYS", level: 79, category: "Simulation" },
         { name: "SolidWorks", level: 84, category: "CAD" },
         { name: "Python", level: 61, category: "Languages" },
         { name: "ROS", level: 55, category: "Robotics" },
      ],
      interests: ["Thermal Engineering", "Mentoring", "Motorcycles"],
      joins: [{ slug: "robotics-club", status: "approved" }, { slug: "quantum-computing", status: "approved" }],
      follows: [],
      lastLoginDaysAgo: 3.7,
   },
   {
      email: "zoya.ahmed@college.edu", username: "zoyaahmed", name: "Zoya Ahmed",
      phone: "+91 99015 05673",
      profile: {
         department: "Computer Science & Engineering", year: "2",
         bio: "Interested in ML fairness after a course project that went badly in an instructive way. Now runs the AI club's ethics reading slot, which is better attended than anyone expected.",
         linkedinUrl: "https://linkedin.com/in/zoya-ahmed-ml",
         githubUrl: "https://github.com/zoyaahmed",
         portfolioUrl: "https://zoyaahmed.ai",
         tags: ["ML Fairness", "Research", "Writing"],
      },
      skills: [
         { name: "Python", level: 72, category: "Languages" },
         { name: "scikit-learn", level: 68, category: "ML" },
         { name: "Technical Writing", level: 77, category: "Writing" },
      ],
      interests: ["AI Ethics", "Policy", "Reading"],
      joins: [{ slug: "ai-club", status: "approved" }, { slug: "quantum-computing", status: "approved" }],
      follows: ["literary-society", "e-cell"],
      lastLoginDaysAgo: 0.35,
   },
   {
      email: "aryan.kapoor@college.edu", username: "aryankapoor", name: "Aryan Kapoor",
      phone: "+91 99015 16284",
      profile: {
         department: "Electrical & Electronics", year: "4",
         bio: "Final year EEE. Built the campus solar monitoring rig as a course project and never took it down; it has been logging continuously for two years now.",
         linkedinUrl: "https://linkedin.com/in/aryan-kapoor-eee",
         githubUrl: "https://github.com/aryankapoor",
         portfolioUrl: "https://aryankapoor.energy",
         tags: ["Renewables", "IoT", "Instrumentation"],
      },
      skills: [
         { name: "Embedded Systems", level: 77, category: "Hardware" },
         { name: "IoT", level: 73, category: "Hardware" },
         { name: "Python", level: 66, category: "Languages" },
         { name: "Grafana", level: 58, category: "Tools" },
      ],
      interests: ["Renewable Energy", "IoT", "Photography"],
      joins: [{ slug: "robotics-club", status: "approved" }, { slug: "photography-club", status: "approved" }],
      follows: ["ai-club"],
      lastLoginDaysAgo: 5.1,
   },
   {
      email: "sara.thomas@college.edu", username: "sarathomas", name: "Sara Thomas",
      phone: "+91 99015 27390",
      profile: {
         department: "Management Studies", year: "2",
         bio: "Handles E-Cell's events end to end — venue, sponsors, the follow-up nobody else wants to do. Ran last year's demo day for two hundred people on a budget of almost nothing.",
         linkedinUrl: "https://linkedin.com/in/sara-thomas-events",
         githubUrl: "https://github.com/sarathomas",
         portfolioUrl: "https://sarathomas.events",
         tags: ["Events", "Sponsorship", "Operations"],
      },
      skills: [
         { name: "Event Management", level: 85, category: "Operations" },
         { name: "Negotiation", level: 71, category: "Business" },
         { name: "Notion", level: 80, category: "Tools" },
      ],
      interests: ["Events", "Startups", "Food"],
      joins: [{ slug: "e-cell", status: "approved" }, { slug: "music-club", status: "approved" }],
      follows: ["design-studio"],
      lastLoginDaysAgo: 0.55,
   },
   {
      email: "ved.prakash@college.edu", username: "vedprakash", name: "Ved Prakash",
      phone: "+91 99015 38845",
      profile: {
         department: "Civil Engineering", year: "3",
         bio: "Documents everything. Shoots the club's matches, the fests, the convocation — if it happened on campus this year there is a good chance he has a photo of it.",
         linkedinUrl: "https://linkedin.com/in/ved-prakash-photo",
         githubUrl: "https://github.com/vedprakash",
         portfolioUrl: "https://vedprakash.gallery",
         tags: ["Documentary", "Sports Photography", "Archives"],
      },
      skills: [
         { name: "Photography", level: 84, category: "Photography" },
         { name: "Lightroom", level: 79, category: "Photography" },
         { name: "Archival Cataloguing", level: 62, category: "Operations" },
      ],
      interests: ["Photography", "History", "Cricket"],
      joins: [{ slug: "photography-club", status: "approved" }, { slug: "sports-council", status: "approved" }],
      follows: ["film-makers"],
      lastLoginDaysAgo: 2.2,
   },
   {
      email: "leela.rajan@college.edu", username: "leelarajan", name: "Leela Rajan",
      phone: "+91 99015 49107",
      profile: {
         department: "Humanities & Social Sciences", year: "4",
         bio: "Directs. Two shorts in festival circulation and a third in edit. Convinced the film club to shoot on location instead of in the studio, which was more work and much better.",
         linkedinUrl: "https://linkedin.com/in/leela-rajan-film",
         githubUrl: "https://github.com/leelarajan",
         portfolioUrl: "https://leelarajan.film",
         tags: ["Directing", "Screenwriting", "Festivals"],
      },
      skills: [
         { name: "Directing", level: 82, category: "Film" },
         { name: "Screenwriting", level: 86, category: "Film" },
         { name: "Premiere Pro", level: 70, category: "Video" },
      ],
      interests: ["Cinema", "Writing", "Theatre"],
      joins: [{ slug: "film-makers", status: "approved" }, { slug: "literary-society", status: "approved" }],
      follows: ["music-club", "design-studio"],
      lastLoginDaysAgo: 1.35,
   },
);

// A few memberships that ended, so the Members page's "Past" tab and its rejected /
// left / removed sub-filters have something real behind them. `by` is the coordinator
// email recorded on a removal; a voluntary leave records nobody.
const PAST_MEMBERSHIPS = [
   { student: "ayaan.khan@college.edu", club: "design-studio", status: "left", daysAgo: 62 },
   { student: "dhruv.agarwal@college.edu", club: "codeforces-nitk", status: "left", daysAgo: 41 },
   { student: "saanvi.gupta@college.edu", club: "robotics-club", status: "rejected", daysAgo: 55 },
   { student: "riya.das@college.edu", club: "e-cell", status: "rejected", daysAgo: 33 },
   { student: "rohan.bhat@college.edu", club: "film-makers", status: "removed", daysAgo: 27, by: "farah.qureshi@college.edu" },
   { student: "vihaan.chauhan@college.edu", club: "photography-club", status: "removed", daysAgo: 18, by: "vikram.joshi@college.edu" },
   { student: "tara.mishra@college.edu", club: "music-club", status: "left", daysAgo: 12 },
];

module.exports = { FACULTY, STUDENTS, PAST_MEMBERSHIPS };
